baseURL: "https://liyingli-math.github.io"
defaultContentLanguage : "en"
title: "LI Liying's Homepage"

     
theme: "PaperMod"

params:
  mainSections:
       
  math: true
  ## code
  ShowCodeCopyButtons: true

  ## toc
  showtoc: false
  tocopen: false
  UseHugoToc: false

  ## additional info
  # ShowPostNavLinks: true
  # ShowWordCount: true
  # ShowReadingTime: true

  ## layout
  # ShowBreadCrumbs: true
  hideSummary: true

  ## use chroma for markup
  assets:
    disableHLJS: true

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: personal
      name: CV
      url: /cv/
      weight: 5
    - identifier: research
      name: Research
      url: /research/
      weight: 10
    - identifier: teaching
      name: Teaching
      url: /teaching/all-courses
      weight: 20
    - identifier: emacs
      name: Emacs
      url: /emacs/
      weight: 30
    # - identifier: sustech
    #   name: SUSTech
    #   url: "https://math.sustech.edu.cn/?lang=en"
    #   weight: 99

## use chroma for syntax highlighting
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai
